volumes:
  database:

services:
    testing:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - "1433:1433"
        tmpfs:
        - /var/opt/mssql
        volumes:
        - ./docker/mssql:/docker-entrypoint-initdb.d
        environment:
            MSSQL_SA_PASSWORD: secret*12345
            ACCEPT_EULA: Y
        command: ["--innodb_flush_log_at_trx_commit=2"]
    build-api:
        build:
            context: ./api/
            dockerfile: nginx.docker
        ports:
            - "8000:80"
        links:
            - build-fpm
        volumes:
            - ./api/:/var/www
    build-fpm:
        build:
            context: ./api/
        tmpfs:
            - /tmp
        volumes:
            - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./api:/var/www
            - ~/.ssh:/home/ubuntu/.ssh
        environment:
            - "DB_PORT=3306"
            - "DB_TESTING_HOST=testing"
        user: ubuntu
    build-frontend:
        build:
            context: ./frontend
        ports:
            - 8080:8080
        volumes:
            - ./frontend/:/opt/app
        user: node
    build-mail:
        image: maildev/maildev
        ports:
            - "8025:80"
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS

