volumes:
  sqlserver_data:

services:
  app-fpm:
    build:
      context: ./api/
      dockerfile: Dockerfile.prod
    image: invoice-manager-build-fpm
    expose:
      - "9000"
  app-api:
    build:
      context: ./api/
      dockerfile: nginx.docker
    image: invoice-manager-build-api
    ports:
      - "8000:80"
    depends_on:
      - app-fpm
  app-frontend:
    build:
      context: ./frontend/
      dockerfile: prod.docker
    image: invoice-manager-build-frontend
    ports:
      - "8080:80"
