volumes:
  sqlserver_data:

services:
  app-fpm:
    build:
      context: ./api/
      dockerfile: Dockerfile.prod
    image: invoice-manager-build-fpm
    expose:
      - "9000"
  app-api:
    build:
      context: ./api/
      dockerfile: nginx.docker
    image: invoice-manager-build-api
    ports:
      - "8000:80"
    depends_on:
      - app-fpm
  app-frontend:
    build:
      context: ./frontend/
      dockerfile: prod.docker
    image: invoice-manager-build-frontend
    ports:
      - "8080:80"
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        MSSQL_SA_PASSWORD: secret*12345
        ACCEPT_EULA: Y
    ports:
        - "1433:1433"
    volumes:
        - sqlserver_data:/var/opt/mssql
    restart: unless-stopped
